CREATE USER SYL IDENTIFIED BY oracleishard;
GRANT CONNECT, CREATE SESSION, UNLIMITED TABLESPACE TO SYL;

-- BEGIN
--     FOR tt IN (SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER='SYL') LOOP
--         EXECUTE IMMEDIATE 'GRANT ALL ON SYL.'||tt.TABLE_NAME||' TO SYL';
--     END LOOP;
-- END;
-- /